// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFkkmVB1KtkOoRKPv5Kxsmm2ML2df6iiI',
    appId: '1:271768816371:web:5d8fafee64ef0f3e120586',
    messagingSenderId: '271768816371',
    projectId: 'walpaper-app-93ef6',
    authDomain: 'walpaper-app-93ef6.firebaseapp.com',
    storageBucket: 'walpaper-app-93ef6.appspot.com',
    measurementId: 'G-YQTRVN54TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiLZEupPnR0HSq0a1pN0Kt8q2QTEfUIjE',
    appId: '1:271768816371:android:551eb97d8c4483d5120586',
    messagingSenderId: '271768816371',
    projectId: 'walpaper-app-93ef6',
    storageBucket: 'walpaper-app-93ef6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2ukZp2ZqAU0f1d0y46pTcL0w6_Qx_sIY',
    appId: '1:271768816371:ios:f7cbeb3b9ffdf536120586',
    messagingSenderId: '271768816371',
    projectId: 'walpaper-app-93ef6',
    storageBucket: 'walpaper-app-93ef6.appspot.com',
    iosClientId: '271768816371-7288fqhuol6rpfu5m6nc98tc09munrs4.apps.googleusercontent.com',
    iosBundleId: 'com.example.walpapersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2ukZp2ZqAU0f1d0y46pTcL0w6_Qx_sIY',
    appId: '1:271768816371:ios:086274f4978d70c3120586',
    messagingSenderId: '271768816371',
    projectId: 'walpaper-app-93ef6',
    storageBucket: 'walpaper-app-93ef6.appspot.com',
    iosClientId: '271768816371-ge5njtijf9rvr798r3otoclv436ajjrj.apps.googleusercontent.com',
    iosBundleId: 'com.walpaper.app',
  );
}
